---
title: "git_00"
author: "Shaun Ikeuchi"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
All in the golden afternoon 

Full leisurely we glide; 

For both our oars, with little skill, 

By little arms are plied, 

While little hands make vain pretence 

Our wanderings to guide. 

## Second Verse
Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood 

And looked down one as far as I could

To where it bent in the undergrowth;

## Third Verse
The sun was shining on the sea, 

Shining with all his might: 

He did his very best to make 

The billows smooth and bright — 

And this was odd, because it was 

The middle of the night.

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If you can keep your head when all about you

Are losing theirs and blaming it on you,

If you can trust yourself when all men doubt you,

But make allowance for their doubting too;

If you can wait and not be tired by waiting,

Or being lied about, don’t deal in lies,

Or being hated, don’t give way to hating,

And yet don’t look too good, nor talk too wise:

If you can dream—and not make dreams your master;

If you can think—and not make thoughts your aim;

If you can meet with Triumph and Disaster

And treat those two impostors just the same;

If you can bear to hear the truth you’ve spoken

Twisted by knaves to make a trap for fools,

Or watch the things you gave your life to, broken,
